include:
  - board: seeeduino_xiao_ble
    shield: tibiboard30_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: tibiboard30_right
     - board: seeeduino_xiao_ble
    shield: settings_reset


